apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinaa-no-vault
  namespace: tinaa-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinaa-no-vault
  template:
    metadata:
      labels:
        app: tinaa-no-vault
    spec:
      containers:
      - name: tinaa
        image: ghcr.io/aj-geddes/tinaa-playwright-msp:latest
        ports:
        - containerPort: 8765
        env:
        - name: TINAA_MODE
          value: "http"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONPATH
          value: "/app"
        - name: PLAYWRIGHT_BROWSERS_PATH
          value: "/ms-playwright"
        - name: WORKSPACE_PATH
          value: "/mnt/workspace"
        - name: TINAA_ANTHROPIC_API_KEY
          value: "YOUR_ANTHROPIC_API_KEY_HERE"
        - name: TINAA_ANTHROPIC_BASE_URL
          value: "https://api.anthropic.com"
        - name: TINAA_ANTHROPIC_DEFAULT_MODEL
          value: "claude-3-sonnet-20240229"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: workspace
          mountPath: /mnt/workspace
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
          runAsNonRoot: false
          runAsUser: 0
      volumes:
      - name: logs
        emptyDir: {}
      - name: workspace
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tinaa-no-vault
  namespace: tinaa-testing
spec:
  selector:
    app: tinaa-no-vault
  ports:
  - port: 8765
    targetPort: 8765
  type: ClusterIP