# Ruff configuration for TINAA

# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "I", "N", "UP", "B", "A", "C4", "DTZ", "T10", "ISC", "ICN", "PIE", "PT", "RET", "SIM", "ARG", "PD", "PGH", "PL", "TRY", "RUF"]

ignore = [
    "E501",  # Line too long
    "B008",  # Do not perform function calls in argument defaults
    "B904",  # Allow raising without from inside except
    "PLR0913", # Too many arguments
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "build",
    "dist",
    "venv",
]

line-length = 88
target-version = "py310"

[per-file-ignores]
"tests/*" = ["S101", "PLR2004"]  # Allow assert and magic values in tests
"__init__.py" = ["F401"]  # Allow unused imports in __init__ files