apiVersion: v1
kind: Secret
metadata:
  name: tinaa-secret
  namespace: tinaa
type: Opaque
stringData:
  TINAA_API_KEY: "tinaa-dev-key-changeme"
  GITHUB_WEBHOOK_SECRET: ""
  GITHUB_APP_ID: ""
  GITHUB_PRIVATE_KEY: ""
