"""initial schema - 13 tables

Revision ID: fc5241a12fa5
Revises: 
Create Date: 2026-03-21 04:24:32.879464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5241a12fa5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_organizations_slug')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=False)
    op.create_table('products',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('repository_url', sa.String(length=512), nullable=True),
    sa.Column('repository_owner', sa.String(length=255), nullable=True),
    sa.Column('repository_name', sa.String(length=255), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_score_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'archived', name='product_status'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_products_org_slug')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.create_table('alert_rules',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('condition_type', sa.Enum('quality_score_drop', 'test_failure', 'performance_regression', 'endpoint_down', 'security_issue', name='alert_condition_type'), nullable=False),
    sa.Column('threshold', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_product_id'), 'alert_rules', ['product_id'], unique=False)
    op.create_table('environments',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('env_type', sa.Enum('production', 'staging', 'development', 'preview', name='environment_type'), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monitoring_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_id'), 'environments', ['id'], unique=False)
    op.create_index(op.f('ix_environments_product_id'), 'environments', ['product_id'], unique=False)
    op.create_table('playbooks',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='playbook_priority'), nullable=False),
    sa.Column('source', sa.Enum('auto_generated', 'manual', 'hybrid', name='playbook_source'), nullable=False),
    sa.Column('trigger_on_deploy', sa.Boolean(), nullable=False),
    sa.Column('trigger_on_pr', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('assertions', sa.JSON(), nullable=False),
    sa.Column('performance_gates', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.String(length=20), nullable=True),
    sa.Column('affected_paths', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbooks_id'), 'playbooks', ['id'], unique=False)
    op.create_index(op.f('ix_playbooks_product_id'), 'playbooks', ['product_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('alert_rule_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'warning', 'info', name='alert_severity'), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_rule_id'), 'alert_events', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_id'), 'alert_events', ['id'], unique=False)
    op.create_table('deployments',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'success', 'failure', 'error', name='deployment_status'), nullable=False),
    sa.Column('deployment_url', sa.String(length=512), nullable=True),
    sa.Column('github_deployment_id', sa.Integer(), nullable=True),
    sa.Column('deployer', sa.String(length=255), nullable=True),
    sa.Column('triggered_test_runs', sa.JSON(), nullable=False),
    sa.Column('quality_score_delta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_environment_id'), 'deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_product_id'), 'deployments', ['product_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint_type', sa.Enum('page', 'api', 'health', 'websocket', name='endpoint_type'), nullable=True),
    sa.Column('performance_budget_ms', sa.Integer(), nullable=True),
    sa.Column('lcp_budget_ms', sa.Integer(), nullable=True),
    sa.Column('cls_budget', sa.Float(), nullable=True),
    sa.Column('expected_status_code', sa.Integer(), nullable=False),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_environment_id'), 'endpoints', ['environment_id'], unique=False)
    op.create_index(op.f('ix_endpoints_id'), 'endpoints', ['id'], unique=False)
    op.create_table('quality_score_snapshots',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('test_health_score', sa.Float(), nullable=False),
    sa.Column('performance_health_score', sa.Float(), nullable=False),
    sa.Column('security_posture_score', sa.Float(), nullable=False),
    sa.Column('accessibility_score', sa.Float(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('test_pass_rate', sa.Float(), nullable=True),
    sa.Column('coverage_breadth', sa.Float(), nullable=True),
    sa.Column('availability', sa.Float(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_score_snapshots_environment_id'), 'quality_score_snapshots', ['environment_id'], unique=False)
    op.create_index(op.f('ix_quality_score_snapshots_id'), 'quality_score_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_quality_score_snapshots_product_id'), 'quality_score_snapshots', ['product_id'], unique=False)
    op.create_table('test_runs',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.Enum('deployment', 'schedule', 'manual', 'pr', 'anomaly', name='test_run_trigger'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'passed', 'failed', 'error', 'cancelled', name='test_run_status'), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('deployment_url', sa.String(length=512), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('results_summary', sa.JSON(), nullable=False),
    sa.Column('quality_score_before', sa.Float(), nullable=True),
    sa.Column('quality_score_after', sa.Float(), nullable=True),
    sa.Column('artifacts_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_environment_id'), 'test_runs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_test_runs_id'), 'test_runs', ['id'], unique=False)
    op.create_index(op.f('ix_test_runs_playbook_id'), 'test_runs', ['playbook_id'], unique=False)
    op.create_index(op.f('ix_test_runs_product_id'), 'test_runs', ['product_id'], unique=False)
    op.create_table('metric_baselines',
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.Enum('response_time', 'ttfb', 'fcp', 'lcp', 'cls', 'inp', 'availability', 'error_rate', 'status_code', name='metric_type_baseline'), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p95', sa.Float(), nullable=False),
    sa.Column('p99', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_baselines_endpoint_id'), 'metric_baselines', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_metric_baselines_id'), 'metric_baselines', ['id'], unique=False)
    op.create_table('metric_datapoints',
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.Enum('response_time', 'ttfb', 'fcp', 'lcp', 'cls', 'inp', 'availability', 'error_rate', 'status_code', name='metric_type'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_datapoints_endpoint_id'), 'metric_datapoints', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_metric_datapoints_id'), 'metric_datapoints', ['id'], unique=False)
    op.create_index(op.f('ix_metric_datapoints_metric_type'), 'metric_datapoints', ['metric_type'], unique=False)
    op.create_index(op.f('ix_metric_datapoints_timestamp'), 'metric_datapoints', ['timestamp'], unique=False)
    op.create_table('test_results',
    sa.Column('test_run_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('passed', 'failed', 'skipped', 'error', name='test_result_status'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('screenshot_url', sa.String(length=512), nullable=True),
    sa.Column('console_logs', sa.JSON(), nullable=False),
    sa.Column('network_requests', sa.JSON(), nullable=False),
    sa.Column('performance_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_test_run_id'), 'test_results', ['test_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_test_run_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_metric_datapoints_timestamp'), table_name='metric_datapoints')
    op.drop_index(op.f('ix_metric_datapoints_metric_type'), table_name='metric_datapoints')
    op.drop_index(op.f('ix_metric_datapoints_id'), table_name='metric_datapoints')
    op.drop_index(op.f('ix_metric_datapoints_endpoint_id'), table_name='metric_datapoints')
    op.drop_table('metric_datapoints')
    op.drop_index(op.f('ix_metric_baselines_id'), table_name='metric_baselines')
    op.drop_index(op.f('ix_metric_baselines_endpoint_id'), table_name='metric_baselines')
    op.drop_table('metric_baselines')
    op.drop_index(op.f('ix_test_runs_product_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_playbook_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_environment_id'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_quality_score_snapshots_product_id'), table_name='quality_score_snapshots')
    op.drop_index(op.f('ix_quality_score_snapshots_id'), table_name='quality_score_snapshots')
    op.drop_index(op.f('ix_quality_score_snapshots_environment_id'), table_name='quality_score_snapshots')
    op.drop_table('quality_score_snapshots')
    op.drop_index(op.f('ix_endpoints_id'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_environment_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_deployments_product_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_environment_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_alert_events_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_playbooks_product_id'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_id'), table_name='playbooks')
    op.drop_table('playbooks')
    op.drop_index(op.f('ix_environments_product_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_alert_rules_product_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
