apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tinaa-playwright-msp.fullname" . }}
  labels:
    {{- include "tinaa-playwright-msp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tinaa-playwright-msp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tinaa-playwright-msp.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tinaa-playwright-msp.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- with .Values.tinaa.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.tinaa.persistence.logs.enabled }}
            - name: logs
              mountPath: /app/logs
            {{- end }}
            {{- if .Values.tinaa.persistence.workspace.enabled }}
            - name: workspace
              mountPath: {{ .Values.tinaa.persistence.workspace.mountPath | default "/mnt/workspace" }}
            {{- end }}
            {{- if .Values.tinaa.persistence.aiCache.enabled }}
            - name: ai-cache
              mountPath: {{ .Values.tinaa.persistence.aiCache.mountPath | default "/app/ai-cache" }}
            {{- end }}
            {{- if .Values.tinaa.persistence.projectTemplates.enabled }}
            - name: project-templates
              mountPath: {{ .Values.tinaa.persistence.projectTemplates.mountPath | default "/app/templates" }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.tinaa.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Values.tinaa.persistence.logs.existingClaim | default (printf "%s-logs" (include "tinaa-playwright-msp.fullname" .)) }}
        {{- else }}
        - name: logs
          emptyDir: {}
        {{- end }}
        {{- if .Values.tinaa.persistence.workspace.enabled }}
        - name: workspace
          persistentVolumeClaim:
            claimName: {{ .Values.tinaa.persistence.workspace.existingClaim | default (printf "%s-workspace" (include "tinaa-playwright-msp.fullname" .)) }}
        {{- else }}
        - name: workspace
          emptyDir: {}
        {{- end }}
        {{- if .Values.tinaa.persistence.aiCache.enabled }}
        - name: ai-cache
          persistentVolumeClaim:
            claimName: {{ .Values.tinaa.persistence.aiCache.existingClaim | default (printf "%s-ai-cache" (include "tinaa-playwright-msp.fullname" .)) }}
        {{- else }}
        - name: ai-cache
          emptyDir: {}
        {{- end }}
        {{- if .Values.tinaa.persistence.projectTemplates.enabled }}
        - name: project-templates
          persistentVolumeClaim:
            claimName: {{ .Values.tinaa.persistence.projectTemplates.existingClaim | default (printf "%s-project-templates" (include "tinaa-playwright-msp.fullname" .)) }}
        {{- else }}
        - name: project-templates
          emptyDir: {}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
