{{- if .Values.tinaa.persistence.logs.enabled }}
{{- if not .Values.tinaa.persistence.logs.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tinaa-playwright-msp.fullname" . }}-logs
  labels:
    {{- include "tinaa-playwright-msp.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.tinaa.persistence.logs.accessMode }}
  {{- if .Values.tinaa.persistence.logs.storageClass }}
  storageClassName: {{ .Values.tinaa.persistence.logs.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.tinaa.persistence.logs.size }}
{{- end }}
{{- end }}

{{- if .Values.tinaa.persistence.workspace.enabled }}
{{- if not .Values.tinaa.persistence.workspace.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tinaa-playwright-msp.fullname" . }}-workspace
  labels:
    {{- include "tinaa-playwright-msp.labels" . | nindent 4 }}
    component: workspace
spec:
  accessModes:
    - {{ .Values.tinaa.persistence.workspace.accessMode }}
  {{- if .Values.tinaa.persistence.workspace.storageClass }}
  storageClassName: {{ .Values.tinaa.persistence.workspace.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.tinaa.persistence.workspace.size }}
{{- end }}
{{- end }}

{{- if .Values.tinaa.persistence.aiCache.enabled }}
{{- if not .Values.tinaa.persistence.aiCache.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tinaa-playwright-msp.fullname" . }}-ai-cache
  labels:
    {{- include "tinaa-playwright-msp.labels" . | nindent 4 }}
    component: ai-cache
spec:
  accessModes:
    - {{ .Values.tinaa.persistence.aiCache.accessMode }}
  {{- if .Values.tinaa.persistence.aiCache.storageClass }}
  storageClassName: {{ .Values.tinaa.persistence.aiCache.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.tinaa.persistence.aiCache.size }}
{{- end }}
{{- end }}

{{- if .Values.tinaa.persistence.projectTemplates.enabled }}
{{- if not .Values.tinaa.persistence.projectTemplates.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tinaa-playwright-msp.fullname" . }}-project-templates
  labels:
    {{- include "tinaa-playwright-msp.labels" . | nindent 4 }}
    component: project-templates
spec:
  accessModes:
    - {{ .Values.tinaa.persistence.projectTemplates.accessMode }}
  {{- if .Values.tinaa.persistence.projectTemplates.storageClass }}
  storageClassName: {{ .Values.tinaa.persistence.projectTemplates.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.tinaa.persistence.projectTemplates.size }}
{{- end }}
{{- end }}