{{- if .Values.tinaa.secrets.createSecrets }}
# OpenAI Secret
{{- if .Values.tinaa.aiProviders.openai.enabled }}
{{- if not .Values.tinaa.aiProviders.openai.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tinaa-playwright-msp.fullname" . }}-openai-secret
  labels:
    {{- include "tinaa-playwright-msp.labels" . | nindent 4 }}
    component: ai-provider
type: Opaque
data:
  api-key: {{ .Values.tinaa.aiProviders.openai.apiKey | b64enc | quote }}
{{- end }}
{{- end }}

# Anthropic Secret
{{- if .Values.tinaa.aiProviders.anthropic.enabled }}
{{- if not .Values.tinaa.aiProviders.anthropic.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tinaa-playwright-msp.fullname" . }}-anthropic-secret
  labels:
    {{- include "tinaa-playwright-msp.labels" . | nindent 4 }}
    component: ai-provider
type: Opaque
data:
  api-key: {{ .Values.tinaa.aiProviders.anthropic.apiKey | b64enc | quote }}
{{- end }}
{{- end }}

# Git PAT Secret
{{- if .Values.tinaa.git.pat.enabled }}
{{- if not .Values.tinaa.git.pat.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tinaa-playwright-msp.fullname" . }}-git-secret
  labels:
    {{- include "tinaa-playwright-msp.labels" . | nindent 4 }}
    component: git-auth
type: Opaque
data:
  pat-token: {{ .Values.tinaa.git.pat.token | b64enc | quote }}
  username: {{ .Values.tinaa.git.pat.username | default "git" | b64enc | quote }}
{{- end }}
{{- end }}

# GitHub App Secret
{{- if .Values.tinaa.git.githubApp.enabled }}
{{- if not .Values.tinaa.git.githubApp.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tinaa-playwright-msp.fullname" . }}-github-app-secret
  labels:
    {{- include "tinaa-playwright-msp.labels" . | nindent 4 }}
    component: git-auth
type: Opaque
data:
  app-id: {{ .Values.tinaa.git.githubApp.appId | b64enc | quote }}
  installation-id: {{ .Values.tinaa.git.githubApp.installationId | b64enc | quote }}
  private-key: {{ .Values.tinaa.git.githubApp.privateKey | b64enc | quote }}
{{- end }}
{{- end }}

# Database Secret (for PostgreSQL)
{{- if eq .Values.tinaa.database.type "postgresql" }}
{{- if not .Values.tinaa.database.postgresql.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tinaa-playwright-msp.fullname" . }}-database-secret
  labels:
    {{- include "tinaa-playwright-msp.labels" . | nindent 4 }}
    component: database
type: Opaque
data:
  password: {{ .Values.tinaa.database.postgresql.password | b64enc | quote }}
{{- end }}
{{- end }}

{{- end }}