# MkDocs Documentation Deployment
#
# This workflow builds and deploys MkDocs documentation to GitHub Pages

name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main
      - feature/extended-functionality
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements-mkdocs.txt'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements-mkdocs.txt'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job 1: Build MkDocs documentation
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git revision date plugin

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install MkDocs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-mkdocs.txt

      - name: Build MkDocs site
        run: |
          mkdocs build --strict --verbose
          
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation-html
          path: site/
          retention-days: 30

  # Job 2: Deploy to GitHub Pages
  deploy:
    name: Deploy to GitHub Pages
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Job 3: Deploy preview for PRs
  deploy-preview:
    name: Deploy Preview
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation-html
          path: ./site

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=site --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Comment PR with preview link
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📚 Documentation preview deployed! View at: [Preview Link](https://tinaa-docs-preview.netlify.app)'
            })

  # Job 4: Check documentation quality
  check-docs:
    name: Check Documentation Quality
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs

      - name: Validate MkDocs config
        run: |
          mkdocs build --strict 2>&1 | tee build.log || true
          if grep -q "WARNING\|ERROR" build.log; then
            echo "::warning::Documentation build completed with warnings or errors"
            grep -E "WARNING|ERROR" build.log
          fi

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1
        with:
          fail: false
          args: >-
            --verbose
            --no-progress
            --accept 200,204,206
            --timeout 20
            --max-retries 3
            --exclude-all-private
            --exclude "^https://github.com/.*/pull/"
            --exclude "^https://github.com/.*/issues/"
            docs/
            *.md

      - name: Upload link check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: link-check-results
          path: lychee-out.md
          retention-days: 7
