# Quick Check - Ultra-fast feedback for development
name: Quick Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  quick-check:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          # Only install core dependencies for import checks
          pip install fastmcp pydantic fastapi
      
      - name: Quick lint check
        run: |
          # Only check for critical issues
          ruff check . --select=E9,F63,F7,F82 --output-format=github || true
      
      - name: Check imports
        run: |
          # Just verify the code can be imported
          python -c "import app.main; import app.mcp_handler; print('✅ Imports OK')"
      
      - name: Run smoke test
        run: |
          # Run just the fastest tests
          pytest tests/unit/test_imports.py -v --tb=short || true
      
      - name: Summary
        if: always()
        run: |
          echo "✅ Quick check complete - full CI will run next"